### ISSUE TITLE
Map icons don't show when first opened

### ISSUE THREAD

**Issue by jhoo-sag** [SoftwareAG/cumulocity-smart-map-widget-plugin#1]
When the map is first opened, or when doing a hard refresh, the icons don't display correctly until clicking the refresh button on the widget. Then everything works again until doing a hard refresh.

Example when first opening:
![image](https://user-images.githubusercontent.com/96841914/234362038-5e342062-4e88-482c-b10e-e3163b032fae.png)

Example after clicking the widget's refresh button:
![image](https://user-images.githubusercontent.com/96841914/234362115-545bccac-4a30-4fc3-8444-35047c59f26e.png)

Settings for the widget here:
![image](https://user-images.githubusercontent.com/96841914/234362970-6af2e507-5a03-4bc3-9db9-67b00151ca1c.png)

**Comment by DarpanLalani** [comment]
fixed in 1.0.2
